
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: demo_db
  username: root
  password: rootuser
  port: 3306
  host: localhost
  encoding: utf8

# default: &default
#   adapter: postgresql
#   pool: 5
#   timeout: 5000
#
# development:
#   <<: *default
#   database: demo
#   username: dbuser
#   password: dbuser
#   port: 5432
#   host: localhost
#   encoding: utf8
